export const TASKS_LOAD_REQUEST = 'TASKS_LOAD_REQUEST';
export const ADD_NEW_TASK_CAPTION = 'ADD_NEW_TASK_CAPTION';
export const OPEN_FORM_NEW_TASK_CAPTION = 'OPEN_FORM_NEW_TASK_CAPTION';
export const OPEN_FORM_EDIT_TASK_CAPTION = 'OPEN_FORM_EDIT_TASK_CAPTION';
export const OPEN_FORM_TASK_ITEM_EDIT = 'OPEN_FORM_TASK_ITEM_EDIT';
export const OPEN_FORM_TASK_ITEM_NEW = 'OPEN_FORM_TASK_ITEM_NEW';
export const BOOK_LOAD_REQUEST = "BOOK_LOAD_REQUEST";
export const SEARH_TEXT = 'SEARH_TEXT';