export const TASKS_LOAD_REQUEST = 'TASKS_LOAD_REQUEST';
export const ADD_NEW_TASK_CAPTION = 'ADD_NEW_TASK_CAPTION';
export const OPEN_FORM_TASK_CAPTION = 'OPEN_FORM_TASK_CAPTION';
export const OPEN_FORM_TASK_ITEM_EDIT = 'OPEN_FORM_TASK_ITEM_EDIT';
export const OPEN_FORM_TASK_ITEM_NEW = 'OPEN_FORM_TASK_ITEM_NEW';